# Generated by Django 2.0 on 2021-02-23 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间')),
                ('title', models.CharField(max_length=32, verbose_name='博客标题')),
                ('bloginfo', models.TextField(blank=True, null=True, verbose_name='博客说明')),
                ('blogtext', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('viewnum', models.IntegerField(verbose_name='浏览量')),
                ('bloguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloguser', to=settings.AUTH_USER_MODEL, verbose_name='博主')),
            ],
            options={
                'verbose_name': '博客信息',
                'verbose_name_plural': '博客信息',
            },
        ),
    ]
